// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGEUxNQ3eo4mk55vt6j82LaRnY8gsQv4g',
    appId: '1:576110577606:web:05d9d5e0463b02aa0194c7',
    messagingSenderId: '576110577606',
    projectId: 'fir-test-1274f',
    authDomain: 'fir-test-1274f.firebaseapp.com',
    storageBucket: 'fir-test-1274f.firebasestorage.app',
    measurementId: 'G-SN9WQCMZ08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCpEyA294faRwTPmSaarFgrhh7FuT8AA',
    appId: '1:576110577606:android:55abfc9920f10b1d0194c7',
    messagingSenderId: '576110577606',
    projectId: 'fir-test-1274f',
    storageBucket: 'fir-test-1274f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkenXmAzIlpXg6MM8dhC0XNzdNs0y8-2s',
    appId: '1:576110577606:ios:5ce78e30a61bc5470194c7',
    messagingSenderId: '576110577606',
    projectId: 'fir-test-1274f',
    storageBucket: 'fir-test-1274f.firebasestorage.app',
    androidClientId: '576110577606-dqh6nobtj908o85n4ugc80jdj6aqjipe.apps.googleusercontent.com',
    iosClientId: '576110577606-7b3qh3vs04i16pd2pukm3fg6choe4sbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkenXmAzIlpXg6MM8dhC0XNzdNs0y8-2s',
    appId: '1:576110577606:ios:5ce78e30a61bc5470194c7',
    messagingSenderId: '576110577606',
    projectId: 'fir-test-1274f',
    storageBucket: 'fir-test-1274f.firebasestorage.app',
    androidClientId: '576110577606-dqh6nobtj908o85n4ugc80jdj6aqjipe.apps.googleusercontent.com',
    iosClientId: '576110577606-7b3qh3vs04i16pd2pukm3fg6choe4sbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGEUxNQ3eo4mk55vt6j82LaRnY8gsQv4g',
    appId: '1:576110577606:web:adc48db13960422f0194c7',
    messagingSenderId: '576110577606',
    projectId: 'fir-test-1274f',
    authDomain: 'fir-test-1274f.firebaseapp.com',
    storageBucket: 'fir-test-1274f.firebasestorage.app',
    measurementId: 'G-VSK4CCVD1X',
  );
}
